import * as core from '@actions/core';
import * as github from '@actions/github';
import { exec } from 'child_process';

async function captureErrorsAndInfo() {
  try {
    // Capturar errores del pipeline
    let errors: string = '';

    exec('tu_comando_de_pipelines', (error, stdout, stderr) => {
      if (error || stderr) {
        errors = error ? error.message : stderr;
      }
    });

    // Capturar nombre del commit
    const commitName = github.context.payload.head_commit?.message;

    // Obtener el enlace del repositorio
    const repositoryLink = github.context.payload.repository?.html_url;

    // Formatear la informaci贸n capturada
    const errorMessage = errors ? `Errores: ${errors}` : 'No se encontraron errores.';
    const commitMessage = commitName ? `Nombre del commit: ${commitName}` : 'No se pudo obtener el nombre del commit.';
    const repoLink = repositoryLink ? `Enlace del repositorio: ${repositoryLink}` : 'No se pudo obtener el enlace del repositorio.';

    // Imprimir la informaci贸n capturada
    console.log(errorMessage);
    console.log(commitMessage);
    console.log(repoLink);

    // Puedes hacer lo que necesites con esta informaci贸n, como enviarla a Discord
  } catch (error) {
    core.setFailed(`Ocurri贸 un error: ${error.message}`);
  }
}

captureErrorsAndInfo();
